from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import pandas as pd
import joblib


# ============================================================
# 1. Load Trained ML Pipeline
# ============================================================

MODEL_PATH = "customer_segmentation_pipeline.pkl"

try:
    model = joblib.load(MODEL_PATH)
except Exception as e:
    raise RuntimeError(f"Unable to load ML model: {e}")


# ============================================================
# 2. FastAPI Application
# ============================================================

app = FastAPI(
    title="Customer Segmentation API",
    description=(
        "API for customer segmentation using "
        "RFM Analysis and K-Means Clustering."
    ),
    version="1.0.0"
)


# ============================================================
# 3. CORS Configuration
# ============================================================

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],       # Development purpose
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ============================================================
# 4. Pydantic Request Schema
# ============================================================

class CustomerInput(BaseModel):

    Recency: float = Field(
        ...,
        ge=0,
        description="Number of days since the customer's last purchase"
    )

    Frequency: float = Field(
        ...,
        ge=1,
        description="Number of purchases made by the customer"
    )

    Monetary: float = Field(
        ...,
        ge=0,
        description="Total amount spent by the customer"
    )


# ============================================================
# 5. Pydantic Response Schema
# ============================================================

class CustomerPrediction(BaseModel):

    cluster: int
    segment: str
    recommendation: str


# ============================================================
# 6. Root Endpoint
# ============================================================

@app.get("/")
def home():

    return {
        "status": "success",
        "message": "Customer Segmentation API is running"
    }


# ============================================================
# 7. Health Check Endpoint
# ============================================================

@app.get("/health")
def health_check():

    return {
        "status": "healthy",
        "model_loaded": True
    }


# ============================================================
# 8. Prediction Endpoint
# ============================================================

@app.post(
    "/predict",
    response_model=CustomerPrediction
)
def predict_customer(customer: CustomerInput):

    try:

        # ----------------------------------------------------
        # Convert validated Pydantic data into DataFrame
        # ----------------------------------------------------

        input_data = pd.DataFrame(
            [{
                "Recency": customer.Recency,
                "Frequency": customer.Frequency,
                "Monetary": customer.Monetary
            }]
        )


        # ----------------------------------------------------
        # ML Prediction
        # ----------------------------------------------------

        cluster = int(
            model.predict(input_data)[0]
        )


        # ----------------------------------------------------
        # Business Segment Mapping
        # ----------------------------------------------------

        segment_mapping = {

            0: {
                "segment": "Inactive / Lost",
                "recommendation": (
                    "Run reactivation campaigns, "
                    "special discounts and win-back offers."
                )
            },

            1: {
                "segment": "High-Value / Loyal",
                "recommendation": (
                    "Offer loyalty rewards, exclusive deals "
                    "and premium customer benefits."
                )
            },

            2: {
                "segment": "Regular / Low-Value",
                "recommendation": (
                    "Use personalized recommendations, "
                    "cross-selling and targeted promotions."
                )
            }
        }


        # ----------------------------------------------------
        # Validate Model Output
        # ----------------------------------------------------

        if cluster not in segment_mapping:

            raise HTTPException(
                status_code=500,
                detail="Unknown cluster generated by the model."
            )


        result = segment_mapping[cluster]


        # ----------------------------------------------------
        # API Response
        # ----------------------------------------------------

        return CustomerPrediction(
            cluster=cluster,
            segment=result["segment"],
            recommendation=result["recommendation"]
        )


    except HTTPException:
        raise


    except Exception as e:

        raise HTTPException(
            status_code=500,
            detail=f"Prediction failed: {str(e)}"
        )